flags: {}
nix:
  path:
  - nixpkgs=/home/plc/nixpkgs-git/
  pure: true
extra-package-dbs: []
packages:
- '.'
system-ghc: true
extra-deps:
- HUnit-1.3.1.1
- MonadCatchIO-transformers-0.3.1.3
- attoparsec-enumerator-0.3.4
- blaze-builder-enumerator-0.2.1.0
- bytestring-mmap-0.2.2
- data-default-0.5.3
- data-default-instances-base-0.1.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- entropy-0.3.7
- enumerator-0.4.20
- extensible-exceptions-0.1.1.4
- monads-tf-0.1.0.3
- regex-base-0.93.2
- regex-posix-0.95.2
- snap-core-0.9.8.0
- snap-server-0.9.5.1
- threepenny-gui-0.6.0.6
- websockets-0.9.6.2
- websockets-snap-0.9.2.0
- zlib-enum-0.2.3.1
resolver:
  name: custom-snapshot
  location: "./custom-snapshot.yaml"
